services:
  - type: web
    name: myresume-portfolio
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PGHOST
        fromDatabase:
          name: myresume-db
          property: host
      - key: PGPORT
        fromDatabase:
          name: myresume-db
          property: port
      - key: PGUSER
        fromDatabase:
          name: myresume-db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: myresume-db
          property: password
      - key: PGDATABASE
        fromDatabase:
          name: myresume-db
          property: database
      - key: PGSSLMODE
        value: "require"

databases:
  - name: myresume-db
    plan: free
    databaseName: myresume
    user: myresume
